[versions]
# Plugins
kotlin = "2.0.0"
shadow = "8.1.1"

# Libraries
klogging = "0.5.14"
jackson-dataformat-yaml = "2.17.2"
jackson-module-kotlin = "2.17.2"

[libraries]
klogging = { module = "io.klogging:klogging-jvm", version.ref = "klogging" }
jackson-dataformat-yml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson-dataformat-yaml" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }